### ISSUE TITLE
Pretty & log printing of execute() data object

### ISSUE THREAD

**Issue by bmille29** [bmille29/mercy#4]
Short term printing of the data object _(similar to `tree()`)_ is desirable.

The initial things I need are... flow structure & analytics _(\_meta)_ information

- Ability to "pretty print console" for dev debugging purposes.
- Ability to "min print json" for logging purposes

**Comment by bmille29** [comment]
Found a bug with `flow.tree(data)`. 
It appears that the not all flow dependencies get printed.

**Comment by bmille29** [comment]
Another bug...

```javascript
const Mercy = require('./');

const flow = Mercy.flow({
    test: (data, next) => { return next(); },
    test2: (data, next) => { return next(); },
    test3: ['test', (data, next) => { return next(); }]
});

flow.tree();
```

```
/Users/bmiller/workspace/mercy/lib/tree.js:129
            if (val._depends && val._depends.length > 0) {
                    ^

TypeError: Cannot read property '_depends' of null
    at Print.traverse (/Users/bmiller/workspace/bmille29/yaht2/lib/libraries/mercy/lib/tree.js:129:21)
    at Print.traverse (/Users/bmiller/workspace/bmille29/yaht2/lib/libraries/mercy/lib/tree.js:145:18)
    at Print.traverse (/Users/bmiller/workspace/bmille29/yaht2/lib/libraries/mercy/lib/tree.js:145:18)
    at Print.show (/Users/bmiller/workspace/bmille29/yaht2/lib/libraries/mercy/lib/tree.js:110:14)
    at module.exports.internals.Flow.tree (/Users/bmiller/workspace/bmille29/yaht2/lib/libraries/mercy/lib/types/flow.js:586:14)
    at Object.<anonymous> (/Users/bmiller/workspace/bmille29/yaht2/lib/libraries/mercy/foobar.js:9:6)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```
